name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH and deploy
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan 188.166.53.73 >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/id_ed25519 root@188.166.53.73 "cd /root/project && git pull && docker-compose up -d --build"
