name: Deploy to Alibaba VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVET_KEY_ALI }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add VPS to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.VPS_HOST_ALI }} >> ~/.ssh/known_hosts

    - name: Deploy to Alibaba VPS
      run: |
        ssh -i ~/.ssh/id_ed25519 root@47.237.76.4 << 'EOF'
          cd ~/server.1.0 || git clone git@github.com:arsinch/server1.0.git ~/server.1.0
          cd ~/server.1.0
          git pull origin master
          docker-compose down
          docker-compose up -d --build
        EOF
